### ISSUE TITLE
Leave space at top

### ISSUE THREAD

**Issue by Anurag519Narula** [SAKET687/CODER-S_DASHBOARD#9]
leaving space at top will be more user friendly, @SAKET687 please assign me this task and mark this as hacktoberfest, thanks!
![top](https://github.com/user-attachments/assets/b9927dae-ec36-42fd-934c-77ba15eeb042)

**Comment by SAKET687** [comment]
Sorry to say this, but the issue you created is for a very small modification in the CSS. The task for the overall styling modification has already been assigned to someone else. Thank you for your interest in my repository.
